### ISSUE TITLE
您好！我在实现OCR识别功能的时候出现识别文本到一半就截断的现象，请问我该怎么做呢？是需要调整哪里的参数吗？非常感谢！

### ISSUE THREAD

**Issue by Selvaggiar** [LukeForeverYoung/UReader#12]
识别文本到一半就截断的现象，例如:
![image](https://github.com/LukeForeverYoung/UReader/assets/112750450/d89de00e-3746-4ca6-b50c-556b2fa798f2)

图片中含清晰文本，
可是UReader识别结果是：Document understanding refers to automatically extract, analyze and comprehend information from various types of documents, such
识别结果中途截断了。
不知道应该修改代码哪处，非常期待和感谢您的解答！

**Comment by shlyahin** [comment]
Hi,
I have the same question. But I think, the thing is that during FT model was trained to give only short answers. Maximum sequence length is 512 in generation parameters, so it does not limit answer generation.

**Comment by Selvaggiar** [comment]
> Hi, I have the same question. But I think, the thing is that during FT model was trained to give only short answers. Maximum sequence length is 512 in generation parameters, so it does not limit answer generation.

The default value for the parameter，Maximum sequence length， should not be 512; when calling function XXX, it is necessary to specify a value for this parameter.
